### ISSUE TITLE
parser_wordcloud.ipynb에서 generate_db_directory() 에러 관련 

### ISSUE THREAD

**Issue by KBCI-Korea** [pixelhowl/DC_Kizuna_Ai-Gallery_Parser#11]
![image](https://user-images.githubusercontent.com/60613054/217205079-55a82f02-06c0-4977-aaab-598e2fe083e9.png)

database에 generate_db_directory가 없는것 같습니다.

임의로 이전 코드 폴더를 가져왔으나 dup_check.csv가 없어서 코드 실행이 불가했습니다.

**Comment by pixelhowl** [comment]
`generate_db()`로 변경되었습니다. 해당 함수를 사용하시면 됩니다.
해당 파일로 더 이상 실행하지 않아 해당 파일에 미지원 함수가 여럿 있을 수 있습니다.

**Comment by KBCI-Korea** [comment]
빠른 답변 감사합니다, 지원함수 찾아가면서 해결해보면서 막히면 다시 질문 드릴 수 있도록 하겠습니다.
