### ISSUE TITLE
parser_wordcloud.ipynb에서 Kotlinside의 get_auth()  에러 관련

### ISSUE THREAD

**Issue by cutehotdog** [pixelhowl/DC_Kizuna_Ai-Gallery_Parser#12]
![image](https://user-images.githubusercontent.com/126041555/220516420-39192ac3-dd1c-40c5-bdf3-2dc559e20bd9.png)

해당 부분에서 java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: kotlin/jvm/internal/DefaultConstructorMarker
에러가 발생합니다.

Kotlinside의 버전은 KotlinInside-1.14.6.jar 파일을 사용하고 있습니다.

사용하는 Kotlinside을 위해서 세팅이 필요한 부분이 있습니까?

**Comment by pixelhowl** [comment]
네. KotlinInside executable jar가 필요합니다. 
KotlinInside repo에서 제공되는 jar는 plain jar입니다.

현재 repo에서 사용되는 dependency 이외에 KotlinInside와 관련된 추가 질문은 해당 repo에 남겨주시면 감사하겠습니다.

**Comment by cutehotdog** [comment]
네 감사합니다
