### ISSUE TITLE
Youtube parser skipped the last batch due to checking batch_size

### ISSUE THREAD

**Issue by KBCI-Korea** [pixelhowl/DC_Kizuna_Ai-Gallery_Parser#9]
https://github.com/pixelhowl/DC_Kizuna_Ai-Gallery_Parser/blob/b408a684c89dabfcbeca573b959d56bafbf784c8/utils/parsers.py#L329

해당 조건문이면, 마지막 contents가 Batch_size보다 작은 경우, result_ids에 더해지지 않아 count되지 않을것 같습니다.

**Comment by pixelhowl** [comment]
네 맞습니다. 버그 리포트에 감사드립니다.
#10 에서 https://github.com/pixelhowl/DC_Kizuna_Ai-Gallery_Parser/pull/10/commits/82837e25183c40984b4ce3f16bc8c97514472661 으로 수정했습니다. bug fix PR code review해주시면 감사하겠습니다.

**Comment by KBCI-Korea** [comment]
> 네 맞습니다. 버그 리포트에 감사드립니다. #10 에서 [82837e2](https://github.com/pixelhowl/DC_Kizuna_Ai-Gallery_Parser/commit/82837e25183c40984b4ce3f16bc8c97514472661) 으로 수정했습니다. bug fix PR code review해주시면 감사하겠습니다.

else로 해결한다면 batch size와 관계 없이 매번 코드가 수행될 것 같습니다.
실제로 코드 실행 시간이 급격하게 증가하였습니다. 

        result_ids = []
        contents = []
        batch_size = 1000
        counter = 0 # 수정 제안  
        for _, row in tqdm(youtube_df.iterrows(),
                           total=len(youtube_df),
                           desc="Planning parsing"):
            counter = counter + 1 # 수정 제안 
            content = row["제목내용"]
            contents.append(content)
            if len(contents) >= batch_size:
                result_ids.append(parse_contents.remote(contents, yt_regex_id))
                contents = []
            elif counter > (len(youtube_df)//batch_size)*batch_size and len(youtube_df)%batch_size == len(contents): # 수정 제안 
                result_ids.append(parse_contents.remote(contents, yt_regex_id)) # 수정 제안 
                contents = [] # 수정 제안 

조금 세련되지는 못하지만, 이러한 조건문을 추가하는 방법이 있을 것 같습니다.
동작 테스트 결과 len(result_ids)가 기존보다 1증가하고 contents가 추가됨을 확인하였습니다.

다만 제가 github fix에 참여해본 경험이 적어  bug fix PR code review가 이런 방식인지는 잘 모르겠습니다 ㅠㅠ

**Comment by pixelhowl** [comment]
https://github.com/pixelhowl/DC_Kizuna_Ai-Gallery_Parser/pull/10/files 에서 PR에다 suggestion으로 review 넣어주시는게 수정 제안하시기 편하실 겁니다.
![image](https://user-images.githubusercontent.com/50740402/209926273-f3b20773-0b12-4f3b-9a83-f218bc3d1c8b.png)
아니면 직접 PR 올려주셔도 됩니다.

for문 else라서 매번 실행되지 않을 거라 보입니다. 따라서 실행 시간에 문제가 없을 듯 싶은데 확인해보겠습니다. 
혹시 if문 else로 직접 변경하시고 돌리셨나요?

```python
for _, row in tqdm(youtube_df.iterrows(),
                           total=len(youtube_df),
                           desc="Planning parsing"):
    content = row["제목내용"]
    contents.append(content)
    if len(contents) >= batch_size:
        result_ids.append(parse_contents.remote(contents, yt_regex_id))
        contents = []
result_ids.append(parse_contents.remote(contents, yt_regex_id))
```
commit code semantic으로는 위와 같은 형태입니다. for문에서 break가 없어서 else가 없어도 동일합니다.

**Comment by KBCI-Korea** [comment]
넵...for else문을 거의 안써봐서 if else로 자체 수정했었네요.ㅠㅠ

좋은 공부가 되었습니다.

수정하신대로도 동일하게 동작하는 부분 확인했습니다.

감사합니다!!

**Comment by pixelhowl** [comment]
PR branch를 pull하시면 직접 수정하지 않으셔도 됩니다.

수정 제안과 버그 리포트 해주셔서 다시 한번 감사드립니다. 그럼 pr 머지 후 close 하도록 하겠습니다.

**Comment by pixelhowl** [comment]
Resolved in #10
